vote_already_running = "There already is a promotion vote running for the user you wish to promote. Please make sure to vote using reactions and to tell other eligeble members to do the same."
vote_already_trusted = "The user you are trying to promote is already part of the highest possible group."
vote_counted = "I've counted your vote on topic '{}' as {}"
vote_no_permission = "I'm sorry but you are not eligible to vote on this subject."
vote_no_permission_start = "I'm sorry but you are not allowed to start a vote."
vote_already_voted = "I can't count your vote because you have already voted on Vote {}."
vote_doesnt_exist = "There must be a mistake, I cannot find vote {}"
vote_promote_message = "==========================================\nPROMOTE {0} TO TRUSTED? \n Vote initiated by {1}\n Quota needed: {2}\n Vote ID: {3} \n================================================="
vote_general_message = "==========================================\nVote description: {0} \n Vote initiated by {1}\n Quota needed: {2}\n Expiry date: {3} \n================================================="
vote_passed  ="Vote on topic '{}' passed with {} ayys to {} nays."
vote_failed ="Vote on topic '{}' failed with {} nays to {} ayys."
vote_failed_quota ="Vote on topic '{}' finished with {} ayys to {} nays and failed because only {} of {} required votes were casted."